services:
  dev:
    image: tabs-vs-spaces-api/dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_DATABASE=${COSMOS_DATABASE}
    ports:
      - 5000:5000
    volumes:
      - ./:/app/

  release:
    image: tabs-vs-spaces-api/release
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80