FROM mcr.microsoft.com/cbl-mariner/base/python:3.9
RUN /usr/bin/python3.9 -m pip install --upgrade pip
WORKDIR /app
COPY . ./
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT python3 app.py -h 0.0.0.0