name: Trigger auto deployment for tabs-vs-spaces-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tabs-vs-spaces-api-AutoDeployTrigger-e3079faa-7d55-45c2-8348-ea8a4771153d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TABSVSSPACESAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TABSVSSPACESAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TABSVSSPACESAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: brk254.azurecr.io
          registryUsername: ${{ secrets.TABSVSSPACESAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TABSVSSPACESAPI_REGISTRY_PASSWORD }}
          containerAppName: tabs-vs-spaces-api
          resourceGroup: tabs-vs-spaces
          imageToBuild: brk254.azurecr.io/tabs-vs-spaces-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


